In [100]:
import pandas as pd 
import numpy as np
import tensorflow as tf 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler # For feature scaling
from sklearn.metrics import mean_squared_error # For evaluating the model
from tensorflow import keras

In [101]:
data = pd.read_csv("diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [102]:
# separate features and target variable and convert to numpy arrays
X = data.iloc[:,:8].values
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]],
      shape=(768, 8))

In [103]:
y = data.iloc[:,8].values
y[:20]

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1])

In [104]:
X.shape, y.shape

((768, 8), (768,))

In [105]:
np.bincount(y)# check for class imbalance

array([500, 268])

In [106]:
pd.DataFrame(y).value_counts() # check for class imbalance
# this is what np.bincount does internally

0
0    500
1    268
Name: count, dtype: int64

In [107]:
# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42, stratify = y)
# satratify = y ensures that the class distribution is preserved in both training and testing sets

In [108]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((614, 8), (154, 8), (614,), (154,))

In [109]:
X_train[:3]

array([[  1.   ,  90.   ,  62.   ,  12.   ,  43.   ,  27.2  ,   0.58 ,
         24.   ],
       [  5.   , 126.   ,  78.   ,  27.   ,  22.   ,  29.6  ,   0.439,
         40.   ],
       [  2.   , 105.   ,  58.   ,  40.   ,  94.   ,  34.9  ,   0.225,
         25.   ]])

In [110]:
X_test[:3]

array([[  7.   , 159.   ,  64.   ,   0.   ,   0.   ,  27.4  ,   0.294,
         40.   ],
       [ 10.   ,  68.   , 106.   ,  23.   ,  49.   ,  35.5  ,   0.285,
         47.   ],
       [  2.   , 122.   ,  76.   ,  27.   , 200.   ,  35.9  ,   0.483,
         26.   ]])

In [111]:
# standardize the features
# going to have a mean of 0 and a standard deviation of 1

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [112]:
X_train[:3]

array([[-0.85135507, -0.98013068, -0.40478372, -0.55397256, -0.33131928,
        -0.60767846,  0.31079384, -0.79216928],
       [ 0.35657564,  0.16144422,  0.46536842,  0.392787  , -0.52639809,
        -0.30213902, -0.11643851,  0.56103382],
       [-0.5493724 , -0.50447447, -0.62232176,  1.21331196,  0.14244354,
         0.3725939 , -0.76486207, -0.70759409]])

In [113]:
X_test[:3]

array([[ 0.96054099,  1.20788789, -0.29601471, -1.31138021, -0.73076636,
        -0.58221684, -0.55579092,  0.56103382],
       [ 1.86648903, -1.67775979,  1.98813468,  0.14031779, -0.27558248,
         0.44897876, -0.58306107,  1.15306018],
       [-0.5493724 ,  0.03460257,  0.3565994 ,  0.392787  ,  1.12712704,
         0.499902  ,  0.01688223, -0.6230189 ]])

In [114]:
np.random.seed(42)
tf.random.set_seed(42)

### **Create the keras MLP (multi-layer perceptron) model**

* input : shape = (n_features,)
* Dense (5, activation= 'relu')
* Dense (3, activation= 'relu')
* Dense (1, activation= 'sigmoid')(binary output)


In [115]:
X_train.shape[1],

(8,)

In [116]:
model = keras.Sequential([
    keras.layers.Input(shape=(X_train.shape[1],)), # n_features 
    keras.layers.Dense(5, activation='relu'),
    keras.layers.Dense(3, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid') # binary output
])

In [117]:
# compile th model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [118]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 5)              │            45 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 67 (268.00 B)

 Trainable params: 67 (268.00 B)

 Non-trainable params: 0 (0.00 B)

In [119]:
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.3890 - loss: 0.8018 - val_accuracy: 0.3984 - val_loss: 0.7942
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4155 - loss: 0.7749 - val_accuracy: 0.4309 - val_loss: 0.7662
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4358 - loss: 0.7520 - val_accuracy: 0.4472 - val_loss: 0.7408
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4725 - loss: 0.7321 - val_accuracy: 0.4959 - val_loss: 0.7181
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5132 - loss: 0.7146 - val_accuracy: 0.5203 - val_loss: 0.6978
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5438 - loss: 0.6984 - val_accuracy: 0.5772 - val_loss: 0.6789
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5784 - loss: 0.6833 - val_accuracy: 0.6179 - val_loss: 0.6608
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6008 - loss: 0.6688 - val_accuracy: 0.6260 - 

In [120]:
# validating the model
loss, acc = model.evaluate(X_test, y_test, verbose=1)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7532 - loss: 0.4804 


In [121]:
print(f"Test Loss: {loss:.4f}, Test Accuracy: {acc:.4f}")

Test Loss: 0.4804, Test Accuracy: 0.7532


In [122]:
y_pred_prob = model.predict(X_test).ravel()
y_pred = (y_pred_prob >= 0.5).astype(int)
y_pred[:20], y_pred_prob[:20]

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step


(array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0]),
 array([0.6084454 , 0.21310437, 0.34612945, 0.41522095, 0.00507947,
        0.19077621, 0.3906287 , 0.7741231 , 0.02669916, 0.64989144,
        0.09032365, 0.7261558 , 0.05251596, 0.16944127, 0.33025494,
        0.5113739 , 0.5987043 , 0.03906229, 0.61948776, 0.36487564],
       dtype=float32))

In [ ]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score , classification_report

confusion_matrix(y_test, y_pred)

array([[82, 18],
       [20, 34]])

In [124]:
precision_score(y_test, y_pred)

0.6538461538461539

In [125]:
recall_score(y_test, y_pred)

0.6296296296296297

In [126]:
f1_score(y_test, y_pred)

0.6415094339622641

In [128]:
pd.DataFrame(classification_report(y_test, y_pred, output_dict=True))

0          1  accuracy   macro avg  weighted avg
precision    0.803922   0.653846  0.753247    0.728884      0.751298
recall       0.820000   0.629630  0.753247    0.724815      0.753247
f1-score     0.811881   0.641509  0.753247    0.726695      0.752140
support    100.000000  54.000000  0.753247  154.000000    154.000000