In [1]:
import pandas as pd 
import numpy as np
import tensorflow as tf 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler # For feature scaling
from sklearn.metrics import mean_squared_error # For evaluating the model
from tensorflow import keras

In [2]:
data = pd.read_csv("diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
# separate features and target variable and convert to numpy arrays
X = data.iloc[:,:8].values
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]],
      shape=(768, 8))

In [4]:
y = data.iloc[:,8].values
y[:20]

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1])

In [5]:
X.shape, y.shape

((768, 8), (768,))

In [6]:
np.bincount(y)# check for class imbalance

array([500, 268])

In [7]:
pd.DataFrame(y).value_counts() # check for class imbalance
# this is what np.bincount does internally

0
0    500
1    268
Name: count, dtype: int64

In [8]:
# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42, stratify = y)
# satratify = y ensures that the class distribution is preserved in both training and testing sets

In [9]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((614, 8), (154, 8), (614,), (154,))

In [10]:
X_train[:3]

array([[  1.   ,  90.   ,  62.   ,  12.   ,  43.   ,  27.2  ,   0.58 ,
         24.   ],
       [  5.   , 126.   ,  78.   ,  27.   ,  22.   ,  29.6  ,   0.439,
         40.   ],
       [  2.   , 105.   ,  58.   ,  40.   ,  94.   ,  34.9  ,   0.225,
         25.   ]])

In [11]:
X_test[:3]

array([[  7.   , 159.   ,  64.   ,   0.   ,   0.   ,  27.4  ,   0.294,
         40.   ],
       [ 10.   ,  68.   , 106.   ,  23.   ,  49.   ,  35.5  ,   0.285,
         47.   ],
       [  2.   , 122.   ,  76.   ,  27.   , 200.   ,  35.9  ,   0.483,
         26.   ]])

In [12]:
# standardize the features
# going to have a mean of 0 and a standard deviation of 1

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
X_train[:3]

array([[-0.85135507, -0.98013068, -0.40478372, -0.55397256, -0.33131928,
        -0.60767846,  0.31079384, -0.79216928],
       [ 0.35657564,  0.16144422,  0.46536842,  0.392787  , -0.52639809,
        -0.30213902, -0.11643851,  0.56103382],
       [-0.5493724 , -0.50447447, -0.62232176,  1.21331196,  0.14244354,
         0.3725939 , -0.76486207, -0.70759409]])

In [14]:
X_test[:3]

array([[ 0.96054099,  1.20788789, -0.29601471, -1.31138021, -0.73076636,
        -0.58221684, -0.55579092,  0.56103382],
       [ 1.86648903, -1.67775979,  1.98813468,  0.14031779, -0.27558248,
         0.44897876, -0.58306107,  1.15306018],
       [-0.5493724 ,  0.03460257,  0.3565994 ,  0.392787  ,  1.12712704,
         0.499902  ,  0.01688223, -0.6230189 ]])

In [15]:
np.random.seed(42)
tf.random.set_seed(42)

### **Create the keras MLP (multi-layer perceptron) model**

* input : shape = (n_features,)
* Dense (5, activation= 'relu')
* Dense (3, activation= 'relu')
* Dense (1, activation= 'sigmoid')(binary output)


In [16]:
X_train.shape[1],

(8,)

In [17]:
model = keras.Sequential([
    keras.layers.Input(shape=(X_train.shape[1],)), # n_features 
    keras.layers.Dense(5, activation='relu'),
    keras.layers.Dense(3, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid') # binary output
])

In [18]:
# compile th model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 5)              │            45 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 67 (268.00 B)

 Trainable params: 67 (268.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.4338 - loss: 0.7359 - val_accuracy: 0.4634 - val_loss: 0.7270
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5112 - loss: 0.7240 - val_accuracy: 0.5366 - val_loss: 0.7162
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5458 - loss: 0.7144 - val_accuracy: 0.5854 - val_loss: 0.7071
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5580 - loss: 0.7065 - val_accuracy: 0.6585 - val_loss: 0.6994
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5988 - loss: 0.6998 - val_accuracy: 0.6423 - val_loss: 0.6935
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6151 - loss: 0.6939 - val_accuracy: 0.6341 - val_loss: 0.6880
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6354 - loss: 0.6887 - val_accuracy: 0.6504 - val_loss: 0.6830
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6517 - loss: 0.6837 - val_accuracy: 0.6423 - 

In [21]:
# validating the model
loss, acc = model.evaluate(X_test, y_test, verbose=1)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7273 - loss: 0.4975 


In [22]:
print(f"Test Loss: {loss:.4f}, Test Accuracy: {acc:.4f}")

Test Loss: 0.4975, Test Accuracy: 0.7273


In [23]:
y_pred_prob = model.predict(X_test).ravel()
y_pred = (y_pred_prob >= 0.5).astype(int)
y_pred[:20], y_pred_prob[:20]

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step 


(array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0]),
 array([0.6956755 , 0.15027572, 0.21893892, 0.43344703, 0.00862151,
        0.17384242, 0.40677783, 0.88855827, 0.02607203, 0.7864604 ,
        0.08734214, 0.6238782 , 0.03077357, 0.11746462, 0.24299528,
        0.41797784, 0.70606935, 0.04212632, 0.8427591 , 0.43217158],
       dtype=float32))

In [24]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score , classification_report

confusion_matrix(y_test, y_pred)

array([[81, 19],
       [23, 31]])

In [25]:
precision_score(y_test, y_pred)

0.62

In [26]:
recall_score(y_test, y_pred)

0.5740740740740741

In [27]:
f1_score(y_test, y_pred)

0.5961538461538461

In [28]:
pd.DataFrame(classification_report(y_test, y_pred, output_dict=True))

0          1  accuracy   macro avg  weighted avg
precision    0.778846   0.620000  0.727273    0.699423      0.723147
recall       0.810000   0.574074  0.727273    0.692037      0.727273
f1-score     0.794118   0.596154  0.727273    0.695136      0.724702
support    100.000000  54.000000  0.727273  154.000000    154.000000

In [41]:
custom_input = np.array([[5, 116, 74, 0, 0, 25.6, 0.201, 30]])

In [42]:
custom_input_scaled = scaler.transform(custom_input)
custom_input_scaled

array([[ 0.35657564, -0.15565991,  0.24783039, -1.31138021, -0.73076636,
        -0.81137142, -0.83758247, -0.28471812]])

In [50]:
custom_pred_prob = model.predict(custom_input_scaled)[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


In [51]:
custom_pred_prob

np.float32(0.10640032)

In [52]:
custom_pred = int(custom_pred_prob >= 0.5)

In [49]:
print(f"Predicted probability: {custom_pred_prob:.4f}")
print(f"Predicted class: {custom_pred} (1=Diabetic, 0=Non-Diabetic)")

Predicted probability: 0.1064
Predicted class: 0 (1=Diabetic, 0=Non-Diabetic)
