## Part A

classification

01) Import the dataset

• Which Python library and function will you use to import a dataset suitable for
classification?

• How will you separate the features (X) and the target labels (y) from the dataset?

• How can you display:

o The shape of the dataset

o The first few rows of feature data

o The unique target classes

In [117]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier # Multi-layer Perceptron Classifier
from sklearn.metrics import accuracy_score
import numpy as np
import matplotlib.pyplot as plt

# perceptron is a type of artificial neural network that consists of a single layer of output nodes

In [118]:
# import the data
data = pd.read_csv("diabetes.csv")
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [119]:
# independent and dependent
# what are the independent and dependent variables?
# independent variables are the features used for prediction
# dependent variable is the target variable we want to predict

x = data.iloc[:,:8] # [:,:8] means all rows and columns 0 to 7
y = data.iloc[:,8] # [:,8] means all rows and column 8



In [120]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [121]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

02) Split the data into training and testing sets

• Which function will you use to split the dataset into training and testing sets?

• How will you decide the proportion for training and testing data?

• Why might it be important to set a fixed random seed when splitting data?

In [122]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [123]:
x_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
603            7      150             78             29      126  35.2   
118            4       97             60             23        0  28.2   
247            0      165             90             33      680  52.3   
157            1      109             56             21      135  25.2   
468            8      120              0              0        0  30.0   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
192            7      159             66              0        0  30.4   
629            4       94             65             22        0  24.7   
559           11       85             74              0        0  30.1   
684            5      136             82              0        0   0.0   

     DiabetesPedigreeFunction  Age  
603                     0.692   54  
118                     0.443   22  
247                     0.427   23  
157                     0.833   23  
468                     0.183   38  
..                        ...  ...  
763                     0.171   63  
192                     0.383   36  
629                     0.148   21  
559                     0.300   35  
684                     0.640   69  

[614 rows x 8 columns]

In [124]:
y_train

603    1
118    0
247    0
157    0
468    1
      ..
763    0
192    1
629    0
559    0
684    0
Name: Outcome, Length: 614, dtype: int64

In [125]:
print(data["Outcome"].unique())

[1 0]


03) Create the MLP Classifier model object

• Which scikit-learn class is used to create an MLP model for classification?

• How can you define the architecture of the hidden layers and the activation
function?

• Which parameters control the optimization process and the number of training
iterations?

In [126]:
clf = MLPClassifier(alpha=0.01,hidden_layer_sizes=(5,3), random_state=1, max_iter=1000)

# random state is used to ensure reproducibility of results

In [127]:
clf

MLPClassifier(alpha=0.01, hidden_layer_sizes=(5, 3), max_iter=1000,
              random_state=1)

04) Train the model with training data

• Which method will you use to train the model?

• What arguments will you pass to this method?

In [128]:
clf.fit(x_train,y_train)


MLPClassifier(alpha=0.01, hidden_layer_sizes=(5, 3), max_iter=1000,
              random_state=1)

05) Check the accuracy of the testing data

• Which method can directly return the accuracy of the model on the test dataset?

• How can you calculate accuracy using the metrics module in scikit-learn?

• What could cause differences between training accuracy and testing accuracy?

In [129]:
y_pred=clf.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [130]:
accuracy_score(y_test,y_pred)

0.6883116883116883

## Part B

01) Import the dataset

• Which Python library and function will you use to import a dataset suitable for
regression?

• How will you separate the features (X) and the target values (y)?

• How can you display:

o The shape of the dataset

o The first few rows of feature data

o The first few target values

In [131]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor

In [132]:
# import data
data = pd.read_csv("Boston.csv")
data

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0    0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1    0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2    0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3    0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4    0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   
..       ...   ...    ...    ...    ...   ...     ...  ...  ...      ...   
501  0.06263   0.0  11.93  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527   0.0  11.93  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076   0.0  11.93  0.573  6.976  91.0  2.1675    1  273     21.0   
504  0.10959   0.0  11.93  0.573  6.794  89.3  2.3889    1  273     21.0   
505  0.04741   0.0  11.93  0.573  6.030  80.8  2.5050    1  273     21.0   

      black  lstat  medv  
0    396.90   4.98  24.0  
1    396.90   9.14  21.6  
2    392.83   4.03  34.7  
3    394.63   2.94  33.4  
4    396.90   5.33  36.2  
..      ...    ...   ...  
501  391.99   9.67  22.4  
502  396.90   9.08  20.6  
503  396.90   5.64  23.9  
504  393.45   6.48  22.0  
505  396.90   7.88  11.9  

[506 rows x 13 columns]

In [133]:
# independent and dependent

x = data.iloc[:,:12].values
y = data.iloc[:,12].values

In [134]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [135]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

02) Split the data into training and testing sets

• Which function will you use to split the dataset?

• How will you decide the proportion for training and testing data?

In [136]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


In [137]:
x_train

array([[3.5809e-01, 0.0000e+00, 6.2000e+00, ..., 1.7400e+01, 3.9170e+02,
        9.7100e+00],
       [1.5876e-01, 0.0000e+00, 1.0810e+01, ..., 1.9200e+01, 3.7694e+02,
        9.8800e+00],
       [1.1329e-01, 3.0000e+01, 4.9300e+00, ..., 1.6600e+01, 3.9125e+02,
        1.1380e+01],
       ...,
       [1.5098e-01, 0.0000e+00, 1.0010e+01, ..., 1.7800e+01, 3.9451e+02,
        1.0300e+01],
       [2.2927e-01, 0.0000e+00, 6.9100e+00, ..., 1.7900e+01, 3.9274e+02,
        1.8800e+01],
       [1.3914e-01, 0.0000e+00, 4.0500e+00, ..., 1.6600e+01, 3.9690e+02,
        1.4690e+01]])

In [138]:
y_train

array([26.7, 21.7, 22. , 22.9, 10.4, 21.9, 20.6, 26.4, 41.3, 17.2, 27.1,
       20.4, 16.5, 24.4,  8.4, 23. ,  9.7, 50. , 30.5, 12.3, 19.4, 21.2,
       20.3, 18.8, 33.4, 18.5, 19.6, 33.2, 13.1,  7.5, 13.6, 17.4,  8.4,
       35.4, 24. , 13.4, 26.2,  7.2, 13.1, 24.5, 37.2, 25. , 24.1, 16.6,
       32.9, 36.2, 11. ,  7.2, 22.8, 28.7, 14.4, 24.4, 18.1, 22.5, 20.5,
       15.2, 17.4, 13.6,  8.7, 18.2, 35.4, 31.7, 33. , 22.2, 20.4, 23.9,
       25. , 12.7, 29.1, 12. , 17.7, 27. , 20.6, 10.2, 17.5, 19.7, 29.8,
       20.5, 14.9, 10.9, 19.5, 22.7, 19.5, 24.6, 25. , 24.5, 50. , 14.3,
       11.8, 31. , 28.7, 16.2, 43.5, 25. , 22. , 19.9, 22.1, 46. , 22.9,
       20.2, 43.1, 34.6, 13.8, 24.3, 21.5, 24.4, 21.2, 23.8, 26.6, 25.1,
        9.6, 19.4, 19.4,  9.5, 14. , 26.5, 13.8, 34.7, 16.3, 21.7, 17.5,
       15.6, 20.9, 21.7, 12.7, 18.5, 23.7, 19.3, 12.7, 21.6, 23.2, 29.6,
       21.2, 23.8, 17.1, 22. , 36.5, 18.8, 21.9, 23.1, 20.2, 17.4, 37. ,
       24.1, 36.2, 15.7, 32.2, 13.5, 17.9, 13.3, 11

03) Create the MLP Regressor model object

• Which scikit-learn class is used to create an MLP model for regression?

• How can you define the architecture of the hidden layers and the activation
function?

• Which parameters control the optimization process and the number of training
iterations?

In [139]:
rg = MLPRegressor(alpha=0.01, hidden_layer_sizes=(3,2), random_state=1, max_iter=500, activation='identity')

# alpha is the regularization parameter that helps prevent overfitting by penalizing large weights
# hidden_layer_sizes defines the architecture of the neural network
# random_state ensures reproducibility of results
# max_iter is the maximum number of iterations for training
# activation defines the activation function for the hidden layers. And identity is a linear activation function

04) Train the model with training data

• Which method will you use to train the model?

• What arguments will you pass to this method?

In [140]:
rg.fit(x_train, y_train)


MLPRegressor(activation='identity', alpha=0.01, hidden_layer_sizes=(3, 2),
             max_iter=500, random_state=1)

05) Check the error for the testing data

• Which functions from scikit-learn’s metrics module can be used to measure
regression error?

• How would you calculate:

o Mean Squared Error (MSE)

o Root Mean Squared Error (RMSE)

o Mean Absolute Error (MAE)

• What does a smaller error value indicate in regression performance?

In [143]:
y_test

array([22.6, 50. , 23. ,  8.3, 21.2, 19.9, 20.6, 18.7, 16.1, 18.6,  8.8,
       17.2, 14.9, 10.5, 50. , 29. , 23. , 33.3, 29.4, 21. , 23.8, 19.1,
       20.4, 29.1, 19.3, 23.1, 19.6, 19.4, 38.7, 18.7, 14.6, 20. , 20.5,
       20.1, 23.6, 16.8,  5.6, 50. , 14.5, 13.3, 23.9, 20. , 19.8, 13.8,
       16.5, 21.6, 20.3, 17. , 11.8, 27.5, 15.6, 23.1, 24.3, 42.8, 15.6,
       21.7, 17.1, 17.2, 15. , 21.7, 18.6, 21. , 33.1, 31.5, 20.1, 29.8,
       15.2, 15. , 27.5, 22.6, 20. , 21.4, 23.5, 31.2, 23.7,  7.4, 48.3,
       24.4, 22.6, 18.3, 23.3, 17.1, 27.9, 44.8, 50. , 23. , 21.4, 10.2,
       23.3, 23.2, 18.9, 13.4, 21.9, 24.8, 11.9, 24.3, 13.8, 24.7, 14.1,
       18.7, 28.1, 19.8])

In [144]:
y_pred

array([22.81135763, 18.91465302, 23.29508757, 25.26329272, 24.73414651,
       24.63898658, 21.53103425, 23.64726631, 23.62760318,  5.37262173,
       18.28829467,  3.43860245, 16.31004147, 25.13218031, 23.99620368,
       30.6038849 , 21.72701085, 32.04291824, 23.26830376, 24.25089101,
       24.30370539, 21.72797191, 22.37226039, 29.73914968, 25.47755446,
        6.73170448, 23.07421454, 17.15268163, 22.65297804, 21.73244787,
       20.61037651, 21.04592765, 23.06681094, 25.38163361, 20.81338101,
       17.60507457, 25.8098177 , 18.06940257,  4.94674949, 15.77236732,
       27.53458384, 25.7949831 , 21.63841733, 18.3164379 , 21.59087504,
       23.40824084, 25.62648542, 20.39657207, 25.03405038, 23.04306673,
        9.27801517, 25.53289344, 20.86604909, 28.71017027, 19.22403692,
       25.47240151, 29.50042264, 21.83949175, 10.72315915, 23.30739376,
       30.41403134, 24.83430918, 28.03302726, 23.34117131, 24.15190955,
       27.25165185, 18.10949125, 23.02282214, 11.25459906, 26.99

In [ ]:
np.sqrt(mean_squared_error(y_test,y_pred))

# sqrt is used to compute the root mean squared error (RMSE), which is a common metric for regression tasks
# mean_squared_error computes the mean squared error (MSE) between the true and predicted values

10.004253305677796