# Lab 3

# Part A 

In [66]:
import pandas as pd 
import numpy as np
import tensorflow as tf 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier

In [67]:
data = pd.read_csv("diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [69]:
X = data.iloc[:,:8]
y = data.iloc[:,8]

In [70]:
np.bincount(y)

array([500, 268])

In [71]:
X.head()

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0            6      148             72  ...  33.6                     0.627   50
1            1       85             66  ...  26.6                     0.351   31
2            8      183             64  ...  23.3                     0.672   32
3            1       89             66  ...  28.1                     0.167   21
4            0      137             40  ...  43.1                     2.288   33

[5 rows x 8 columns]

In [72]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [73]:
y.unique()

array([1, 0])

In [74]:
X.shape, y.shape

((768, 8), (768,))

In [75]:
# training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    random_state=42,
    test_size=0.2,
    stratify=y
)

In [76]:
clf = MLPClassifier(alpha=0.01, hidden_layer_sizes=(5, 3), random_state=1)

In [77]:
clf

MLPClassifier(alpha=0.01, hidden_layer_sizes=(5, 3), random_state=1)

In [78]:
clf.fit(X_train,y_train)

c:\Users\pkmpp\OneDrive\Documents\python\env\venv_TensorFlow_cpu_1\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(alpha=0.01, hidden_layer_sizes=(5, 3), random_state=1)

In [79]:
y_pred = clf.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [80]:
accuracy_score(y_test,y_pred)

0.6363636363636364

# Part B

In [107]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import accuracy_score, mean_squared_error, root_mean_squared_error, mean_absolute_error

In [89]:
data = pd.read_csv("Boston.csv")
data.head()

crim    zn  indus    nox     rm  ...  tax  ptratio   black  lstat  medv
0  0.00632  18.0   2.31  0.538  6.575  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07  0.469  6.421  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07  0.469  7.185  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18  0.458  6.998  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18  0.458  7.147  ...  222     18.7  396.90   5.33  36.2

[5 rows x 13 columns]

In [90]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   nox      506 non-null    float64
 4   rm       506 non-null    float64
 5   age      506 non-null    float64
 6   dis      506 non-null    float64
 7   rad      506 non-null    int64  
 8   tax      506 non-null    int64  
 9   ptratio  506 non-null    float64
 10  black    506 non-null    float64
 11  lstat    506 non-null    float64
 12  medv     506 non-null    float64
dtypes: float64(11), int64(2)
memory usage: 51.5 KB


In [91]:
X = data.loc[:,:"lstat"]
y = data.loc[:,"medv"]

In [92]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   nox      506 non-null    float64
 4   rm       506 non-null    float64
 5   age      506 non-null    float64
 6   dis      506 non-null    float64
 7   rad      506 non-null    int64  
 8   tax      506 non-null    int64  
 9   ptratio  506 non-null    float64
 10  black    506 non-null    float64
 11  lstat    506 non-null    float64
dtypes: float64(10), int64(2)
memory usage: 47.6 KB


In [93]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 506 entries, 0 to 505
Series name: medv
Non-Null Count  Dtype  
--------------  -----  
506 non-null    float64
dtypes: float64(1)
memory usage: 4.1 KB


In [94]:
X.shape , y.shape

((506, 12), (506,))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, test_size=0.2
)

In [102]:
rg = MLPRegressor(
    alpha=0.01,
    hidden_layer_sizes=(3, 2),
    random_state=42,
    max_iter=300,
    activation="identity",
    verbose=1
)

In [101]:
rg

MLPRegressor(activation='identity', alpha=0.01, hidden_layer_sizes=(3, 2),
             max_iter=300, random_state=42)

In [103]:
rg.fit(X_train,y_train)

Iteration 1, loss = 142.16038939
Iteration 2, loss = 109.15281968
Iteration 3, loss = 83.20166887
Iteration 4, loss = 63.94804389
Iteration 5, loss = 51.58163433
Iteration 6, loss = 45.31373173
Iteration 7, loss = 43.62920475
Iteration 8, loss = 44.06834703
Iteration 9, loss = 45.08722120
Iteration 10, loss = 45.36300234
Iteration 11, loss = 44.75351542
Iteration 12, loss = 43.50610395
Iteration 13, loss = 42.31481001
Iteration 14, loss = 41.22038975
Iteration 15, loss = 41.06496408
Iteration 16, loss = 41.10198610
Iteration 17, loss = 41.34638185
Iteration 18, loss = 41.49098224
Iteration 19, loss = 41.37717122
Iteration 20, loss = 40.99551871
Iteration 21, loss = 40.45209382
Iteration 22, loss = 39.92552922
Iteration 23, loss = 39.54218797
Iteration 24, loss = 39.26909813
Iteration 25, loss = 39.05652603
Iteration 26, loss = 38.70799500
Iteration 27, loss = 38.72228791
Iteration 28, loss = 38.67642763
Iteration 29, loss = 38.44635839
Iteration 30, loss = 38.29707427
Iteration 31, los

MLPRegressor(activation='identity', alpha=0.01, hidden_layer_sizes=(3, 2),
             max_iter=300, random_state=42, verbose=1)

In [105]:
y_pred = rg.predict(X_test)
y_pred

array([26.76369651, 27.65933583, 24.13886848, 20.73445788, 25.75844812,
       23.84095067, 24.19534157, 23.13451954, 27.38502811, 25.04114724,
       25.7474554 , 25.87560081,  2.19410973, 22.68111092, 25.23150051,
       24.46644279, 25.12609835, 21.80195812, 31.41152746, 26.471251  ,
       23.56261149, 26.70661137, 22.43644258, 24.86664247, 22.66345736,
       23.80309446, 22.42364295,  4.49661714, 25.49201148, 24.30187879,
       25.8330994 , 24.72809405, 26.72525581, 27.63302503, 22.11727626,
       18.53166521, 25.84958657, 23.84055523, 22.58085553, 19.36036526,
       22.80330721, 29.77210476, 32.7844574 , 22.84861931, 24.8178397 ,
       26.56402222, 23.41869806, 19.96888894, 26.0397522 , 27.40157756,
       27.06369829, 25.87557672, 25.16713322, 25.80867204, 27.08956212,
       24.23168254, 27.1549913 , 31.22439097, 23.63576087, 25.52787026,
       26.32381859, 31.61855293, 22.0732828 , 16.03475835, 27.6809671 ,
       24.95195672, 26.4798031 , 25.37289338, 29.70857898,  4.42

In [115]:
mean_squared_error(y_test,y_pred)

62.45915195007477

In [ ]:
# RMSE
np.sqrt(mean_squared_error(y_test,y_pred))

np.float64(7.903110270651345)

In [ ]:
#RMSE
root_mean_squared_error(y_test,y_pred)

7.903110270651345

In [112]:
mean_absolute_error(y_test,y_pred)

6.295499794065774